CREATE DATABASE core_bpmn_integr
    WITH 
    OWNER = s_su
    ENCODING = 'UTF8'
    LC_COLLATE = 'ru_RU.UTF-8'
    LC_CTYPE = 'ru_RU.UTF-8'
	  TEMPLATE = template0
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

CREATE ROLE s_ibp WITH
  NOLOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

CREATE ROLE s_ibc WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

ALTER ROLE s_ibc SET search_path TO public, s_ibt, pg_catalog;
ALTER USER s_ibc WITH PASSWORD 's_ibc';