#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function right_index {
    str=$1
    findStr=$2
    len=${#str}
    for ((i = 0; i > -len; i--)); do
        f=${str:$i:1}
        [[ "$f" == "$findStr" ]] && echo $i && break
    done
}

if [ -f $DIR/liquibase.init.properties ]; then
    cd $DIR
    $DIR/../gradlew update -PrunList=init
    if [ $? != 0 ]; then
        echo "Error init errorcode $?"
        exit 1
    fi
    exit 0
fi

read -p "Connection: " -i "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=LOCALHOST)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=NAME)))" -e connectionPreBd
if [ -z "$connectionPreBd" ]; then
    echo "Error empty Connection"
    exit 1
fi
read -p "Superadmin User: " -i "s_su" -e sUser
if [ -z "$sUser" ]; then
    echo "Error empty Superadmin User"
    exit 1
fi
read -p "Superadmin Password: " -i "s_su" -e sPw
if [ -z "$sPw" ]; then
    echo "Error empty Superadmin Password"
    exit 1
fi
read -p "Connection Meta: " -i "jdbc:postgresql://127.0.0.1:5432/core" -e connectionMetaBd
if [ -z "$connectionMetaBd" ]; then
    echo "Error empty Connection Meta"
    exit 1
fi
read -p "Superadmin Meta User: " -i "s_su" -e sMetaUser
if [ -z "$sMetaUser" ]; then
    echo "Error empty Superadmin Meta User"
    exit 1
fi
read -p "Superadmin Meta Password: " -i "s_su" -e sMetaPw
if [ -z "$sMetaPw" ]; then
    echo "Error empty Superadmin Meta Password"
    exit 1
fi
read -p "Prefix Schema: " -i "todo_" -e newSchema

if [ -z "$newSchema" ]; then
    echo "Error empty prefix Schema"
    exit 1
fi

function replaceFn {
    rem1="s/#user.update#/${newSchema^^}P/gi"
    rem2="s/#user.table#/${newSchema^^}T/gi"
    rem3="s/#user.connect#/${newSchema^^}C/gi"
    rem4="s/#user.prefix#/${newSchema^^}/gi"
    rem5="s/#user.admin#/$sUser/gi"
    rem6="s+#schemaConnection#+$connectionPreBd+gi"
    rem7="s/#schemaConnectionAdmin#/$sUser/gi"
    rem8="s/#schemaConnectionAdminPw#/$sPw/gi"
    rem9="s+#metaConnection#+$connectionMetaBd+gi"
    rem10="s/#metaConnectionAdmin#/$sMetaUser/gi"
    rem11="s/#metaConnectionAdminPw#/$sMetaPw/gi"
    sed -i -e "$rem1" -e "$rem2" -e "$rem3" -e "$rem4" -e "$rem5" -e "$rem6" -e "$rem7" -e "$rem8" -e "$rem9" -e "$rem10" -e "$rem11" "$1"
}

replaceFn "$DIR/db.sql"
replaceFn "$DIR/db.changelog.init.xml"

commadLiquibase="$DIR/../gradlew update -PrunList=init -Pliquibase.username=$sPw -Pliquibase.password=$sUser -Pliquibase.url=$connectionPreBd -Pliquibase.driver=oracle.jdbc.OracleDriver"
cd $DIR
$commadLiquibase
if [ $? != 0 ]; then
    echo "Error init $newDataBase errorcode $?"
    exit 1
fi

replaceFn "$DIR/../db.changelog.meta.xml"
replaceFn "$DIR/../db.changelog.schema.xml"
replaceFn "$DIR/../liquibase.meta.properties"
replaceFn "$DIR/../liquibase.schema.properties"
echo "driver: oracle.jdbc.OracleDriver" > $DIR/liquibase.init.properties
echo "url: $connectionPreBd" >> $DIR/liquibase.init.properties
echo "username: $sUser" >> $DIR/liquibase.init.properties
echo "password: $sPw" >> $DIR/liquibase.init.properties
