#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function right_index {
    str=$1
    findStr=$2
    len=${#str}
    for ((i = 0; i > -len; i--)); do
        f=${str:$i:1}
        [[ "$f" == "$findStr" ]] && echo $i && break
    done
}

read -p "Connection: " -i "jdbc:postgresql://127.0.0.1:5432/postgres" -e connectionPreBd
read -p "Superadmin User: " -i "postgres" -e sUser
read -p "Superadmin Password: " -i "postgres" -e sPw
read -p "Connection Meta: " -i "jdbc:postgresql://127.0.0.1:5432/core" -e connectionMetaBd
read -p "Superadmin Meta User: " -i "s_su" -e sMetaUser
read -p "Superadmin Meta Password: " -i "s_su" -e sMetaPw

read -p "Name DataBase: " -e newDataBase

if [ -z "$newDataBase" ]; then
    echo "Error empty DataBase"
    exit 1
fi

l=$(right_index $connectionPreBd  "/")
len=$((${#connectionPreBd}+$l+1))
connectionBd="${connectionPreBd:0:$len}$newDataBase"

read -p "Prefix Schema: " -e newSchema

if [ -z "$newSchema" ]; then
    echo "Error empty prefix Schema"
    exit 1
fi

function replaceFn {
    rem1="s/#user.update#/${newSchema}p/gi"
    rem2="s/#user.table#/${newSchema}t/gi"
    rem3="s/#user.connect#/${newSchema}c/gi"
    rem4="s/#name.db#/$newDataBase/gi"
    rem5="s/#user.admin#/$sUser/gi"
    rem6="s+#schemaConnection#+$connectionBd+gi"
    rem7="s/#schemaConnectionAdmin#/$sUser/gi"
    rem8="s/#schemaConnectionAdminPw#/$sPw/gi"
    rem9="s+#metaConnection#+$connectionMetaBd+gi"
    rem10="s/#metaConnectionAdmin#/$sMetaUser/gi"
    rem11="s/#metaConnectionAdminPw#/$sMetaPw/gi"
    sed -i -e "$rem1" -e "$rem2" -e "$rem3" -e "$rem4" -e "$rem5" -e "$rem6" -e "$rem7" -e "$rem8" -e "$rem9" -e "$rem10" -e "$rem11" "$1"
}

commadLiquibase="$DIR/../liquibase/liquibase --username=$sPw --password=$sUser --url=$connectionPreBd --driver=org.postgresql.Driver --changeLogFile=db.changelog.init.xml update"

$commadLiquibase

replaceFn "$DIR/db.sql"
replaceFn "$DIR/db.changelog.init.xml"
replaceFn "$DIR/../db.changelog.meta.xml"
replaceFn "$DIR/../db.changelog.schema.xml"
replaceFn "$DIR/../liquibase.meta.properties"
replaceFn "$DIR/../liquibase.schema.properties"
