#!/usr/bin/env bash

if [ ! -n "${PATCHER_HOME+x}" ]; then
  # echo "PATCHER_HOME is not set."

  ## resolve links - $0 may be a symlink
  PRG="$0"
  while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
  done


  PATCHER_HOME=`dirname "$PRG"`

  # make it fully qualified
  PATCHER_HOME=`cd "$PATCHER_HOME" && pwd`
fi

 
# build classpath from all jars in lib
if [ -f /usr/bin/cygpath ]; then
  CP=.
  for i in "$PATCHER_HOME"/patcher-core*.jar; do
    i=`cygpath --windows "$i"`
    CP="$CP;$i"
  done
  for i in "$PATCHER_HOME"/lib/*.jar; do
    i=`cygpath --windows "$i"`
    CP="$CP;$i"
  done
else
  if [[ $(uname) = MINGW* ]]; then
    CP_SEPARATOR=";"
  else
    CP_SEPARATOR=":"
  fi
  CP=.
  for i in "$PATCHER_HOME"/patcher-core*.jar; do
    CP="$CP""$CP_SEPARATOR""$i"
  done
  CP="$CP""$CP_SEPARATOR""$PATCHER_HOME/lib/"
  for i in "$PATCHER_HOME"/lib/*.jar; do
    CP="$CP""$CP_SEPARATOR""$i"
  done
fi

# add any JVM options here
JAVA_OPTS="${JAVA_OPTS-}"

java -cp "$CP" -Dfile.encoding=UTF8 -Djaxb.encoding=UTF-8 -Duser.timezone=GMT+0 $JAVA_OPTS ru.opencore.patcher.MainKt ${1+"$@"}


